# This file contains the knowledge base for our travel advisory system.

knowledge_base = [
    {
        'Place' : 'Paris',
        'Country' : 'France',
        'Continent' : 'Europe',
        'Language' : ['French', 'English'],
        'Currency' : 'Euro',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Summer'],
        'Expected_budget' : 'High',
    },
    {
        'Place' : 'Tokyo',
        'Country' : 'Japan',
        'Continent' : 'Asia',
        'Language' : ['Japanese', 'English'],
        'Currency' : 'Japanese Yen',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Autumn'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Cancun',
        'Country' : 'Mexico',
        'Continent' : 'North America',
        'Language' : ['Spanish', 'English'],
        'Currency' : 'Mexican Peso',
        'Visa' : 'No',
        'Season_to_visit': ['Winter', 'Spring'],
        'Expected_budget' : 'Low',
    },
     {
        'Place' : 'Rome',
        'Country' : 'Italy',
        'Continent' : 'Europe',
        'Language' : ['Italian', 'English'],
        'Currency' : 'Euro',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Fall'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'New York City',
        'Country' : 'United States',
        'Continent' : 'North America',
        'Language' : ['English', 'Spanish'],
        'Currency' : 'US Dollar',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Fall'],
        'Expected_budget' : 'High',
    },
    {
        'Place' : 'Sydney',
        'Country' : 'Australia',
        'Continent' : 'Australia',
        'Language' : ['English'],
        'Currency' : 'Australian Dollar',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Summer'],
        'Expected_budget' : 'High',
    },
     {
        'Place' : 'Bangkok',
        'Country' : 'Thailand',
        'Continent' : 'Asia',
        'Language' : ['Thai', 'English'],
        'Currency' : 'Thai Baht',
        'Visa' : 'Yes',
        'Season_to_visit': ['Winter', 'Summer'],
        'Expected_budget' : 'Low',
    },
    {
        'Place' : 'Beijing',
        'Country' : 'China',
        'Continent' : 'Asia',
        'Language' : ['Mandarin', 'English'],
        'Currency' : 'Chinese Yuan',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Autumn'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Seoul',
        'Country' : 'South Korea',
        'Continent' : 'Asia',
        'Language' : ['Korean', 'English'],
        'Currency' : 'Korean Won',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Autumn'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Rio de Janeiro',
        'Country' : 'Brazil',
        'Continent' : 'South America',
        'Language' : ['Portuguese', 'English'],
        'Currency' : 'Brazilian Real',
        'Visa' : 'No',
        'Season_to_visit': ['Summer', 'Fall'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Machu Picchu',
        'Country' : 'Peru',
        'Continent' : 'South America',
        'Language' : ['Spanish', 'Quechua'],
        'Currency' : 'Peruvian Nuevo Sol',
        'Visa' : 'No',
        'Season_to_visit': ['Spring', 'Autumn'],
        'Expected_budget' : 'High',
    },
    {
        'Place' : 'Buenos Aires',
        'Country' : 'Argentina',
        'Continent' : 'South America',
        'Language' : ['Spanish', 'English'],
        'Currency' : 'Argentine Peso',
        'Visa' : 'No',
        'Season_to_visit': ['Spring', 'Fall'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Cusco',
        'Country' : 'Peru',
        'Continent' : 'South America',
        'Language' : ['Spanish', 'Quechua'],
        'Currency' : 'Peruvian Nuevo Sol',
        'Visa' : 'No',
        'Season_to_visit': ['Spring', 'Autumn'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Santiago',
        'Country' : 'Chile',
        'Continent' : 'South America',
        'Language' : ['Spanish', 'English'],
        'Currency' : 'Chilean Peso',
        'Visa' : 'No',
        'Season_to_visit': ['Spring', 'Summer'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Montreal',
        'Country' : 'Canada',
        'Continent' : 'North America',
        'Language' : ['French', 'English'],
        'Currency' : 'Canadian Dollar',
        'Visa' : 'Yes',
        'Season_to_visit': ['Summer', 'Autumn'],
        'Expected_budget' : 'Medium',
    },
    {
        'Place' : 'Los Angeles',
        'Country' : 'United States',
        'Continent' : 'North America',
        'Language' : ['English', 'Spanish'],
        'Currency' : 'US Dollar',
        'Visa' : 'Yes',
        'Season_to_visit': ['Spring', 'Summer'],
        'Expected_budget' : 'Medium',
    }
]
